### PR TITLE
dynamic about page

### PR DESCRIPTION
**Pull request by beargreenholtz**

### CODE REVIEW

**Comment by amir-ben-shimol** [comment]
No description - won't review.
@beargreenholtz

**Comment by beargreenholtz** [comment]
This is the markdown for strapi:

description:

- ## Story is our Method.

- We solve complex messaging challenges by translating those messages and stories into inspiring and engaging content for the multi-channeled world, connecting you with the human that resides on the other side of the screen

- ## Tailor made production.

-  In all cases we will build the entire production according to the client needs, considering the budget and the purpose of the project, producing a perfect film as only 'Spring' knows.
 
- In all cases we will build the entire production according to the client needs, considering the budget and the purpose of the project, producing a perfect film as only 'Spring' knows

* ## Connection is our Mission.

* There are productions we carry out at the logistical level when on the other side there is a ready creative plan or an advertising agency that leads the process, as well as projects that we develop and produce from the initial idea until the final result.

* ## Authenticity is our Message.

* Everything we craft and create is filled with an authentic purpose. A purpose to engage, to inspire, and to drive both emotion and action from your audience

descriptionSecond:

***

# Our Role:

There are productions we carry out at the logistical level when on the other side there is a ready creative plan or an advertising agency that leads the process, as well as projects that we develop and produce from the initial idea until the final result.

In all cases we will build the entire production according to the client needs, considering the budget and the purpose of the project, producing a perfect film as only 'Spring' knows.

## Content Development

Content creation is the primary purpose of a video production company. The production crew starts with a concept, and once that’s finalized, We bring it to life through video.

***

## Scriptwriting

Compelling videos need a compelling script. And whatever the video's goal is, whether that be marketing or educational, the script should accomplish it.

***

## Casting & Hiring

Most companies hire talents like actors, voice actors, and extras from outside. We have connections to talent agencies for this purpose.

***

## Planning and Logistics

The agency project manager handles planning and logistics and works alongside the director and creative team.

*** 

## Production

The shooting day is the most exciting and complex stage of the process. Our professional team brings the script and the creative vision to life with strict attention to schedules, technical and visual aspects.

***

## Post production

We know the value of investing in the editing stage. We offer comprehensive editing services with skilled editors who understand the importance of creativity, emotion, sound and color corrections, accompanied by a post producer and editorial director at every stage until the final touch.

***

descriptionIcon:
Our services are like a puzzle. You can have only one piece or put together the whole thing and get the best of creative digital agency and video production company with a single touch-point.

**Comment by beargreenholtz** [comment]
The changes are:

Adding dynamic text that comes from strapi with a markdown format + styling the page.

**Comment by beargreenholtz** [comment]
Please check the backend new branch: "dynamic-about-page" and merge it to main.

**Pull request closed without merging**
