### PR TITLE
remove slogan, chnage mobile categories

### PR DESCRIPTION
**Pull request by beargreenholtz**

### CODE REVIEW

**Review by amir-ben-shimol — COMMENTED** [review]
UI review first on UI changes

Please check @roy-shiloh 
`yarn start` command to run the project

**Comment by roy-shiloh** [comment]
image

Fix mobile category margins 

Figma:
https://www.figma.com/file/Dt3pgaJ1NnTjWivDFn29xl/Spring-Portfolio?type=design&node-id=831%3A876&t=3s6I0J6bXDnAxIsB-1

**Review by roy-shiloh — CHANGES_REQUESTED** [review]
image

Fix mobile category margins 

Figma:
https://www.figma.com/file/Dt3pgaJ1NnTjWivDFn29xl/Spring-Portfolio?type=design&node-id=831%3A876&t=3s6I0J6bXDnAxIsB-1

**Comment by beargreenholtz** [comment]
image

???? Already has margin

**Pull request merged**
